export type HubSpotSubmissionField = {
  name: string;
  value: string;
};

export const SAMPLE_SUBMISSION_ERROR =
  "Please use real applicant details. Obvious sample/test data is blocked so it doesn't get marked as spam.";

const fakeEmailDomains = new Set([
  "example.com",
  "example.net",
  "example.org",
  "test.com",
  "testing.com",
  "sample.com",
  "fake.com",
  "invalid.com",
  "mailinator.com",
  "tempmail.com",
  "10minutemail.com",
  "yopmail.com",
]);

const sampleTextPatterns = [
  /\blorem ipsum\b/i,
  /\b(this is|this'?s|just|only)\s+(a\s+)?(test|sample)\b/i,
  /\b(test|sample|dummy|fake|placeholder)\s+(submission|entry|lead|data|story|application)\b/i,
  /\b(ai generated|generated by ai|created by claude|from claude)\b/i,
];

function fieldValue(fields: HubSpotSubmissionField[], matcher: RegExp) {
  return fields.find((field) => matcher.test(field.name))?.value.trim() ?? "";
}

function emailDomain(email: string) {
  const domain = email.toLowerCase().split("@")[1]?.trim();
  return domain || "";
}

export function getSampleSubmissionIssue(fields: HubSpotSubmissionField[]) {
  const email = fieldValue(fields, /^email$/i);
  const domain = emailDomain(email);

  if (domain && fakeEmailDomains.has(domain)) {
    return SAMPLE_SUBMISSION_ERROR;
  }

  const firstName = fieldValue(fields, /^first_?name$|^firstname$/i);
  const lastName = fieldValue(fields, /^last_?name$|^lastname$/i);
  const fullName = [firstName, lastName].filter(Boolean).join(" ") || fieldValue(fields, /^name$/i);

  if (/^(john|jane)\s+doe$/i.test(fullName)) {
    return SAMPLE_SUBMISSION_ERROR;
  }

  const company = fieldValue(fields, /^company$|companyname/i);
  if (/^(acme|example|test|sample|dummy|fake)(\s+(corp|company|co|inc|llc|ltd))?$/i.test(company)) {
    return SAMPLE_SUBMISSION_ERROR;
  }

  const combinedText = fields.map((field) => field.value).join("\n");
  if (sampleTextPatterns.some((pattern) => pattern.test(combinedText))) {
    return SAMPLE_SUBMISSION_ERROR;
  }

  return null;
}