/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CriteriaRouteImport } from './routes/criteria'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as WinnerResourcesTokenRouteImport } from './routes/winner-resources.$token'

const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CriteriaRoute = CriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinnerResourcesTokenRoute = WinnerResourcesTokenRouteImport.update({
  id: '/winner-resources/$token',
  path: '/winner-resources/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/criteria': typeof CriteriaRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/winners': typeof WinnersRoute
  '/winner-resources/$token': typeof WinnerResourcesTokenRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/criteria': typeof CriteriaRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/winners': typeof WinnersRoute
  '/winner-resources/$token': typeof WinnerResourcesTokenRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/criteria': typeof CriteriaRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/winners': typeof WinnersRoute
  '/winner-resources/$token': typeof WinnerResourcesTokenRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/criteria'
    | '/faq'
    | '/methodology'
    | '/pricing'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/winners'
    | '/winner-resources/$token'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/criteria'
    | '/faq'
    | '/methodology'
    | '/pricing'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/winners'
    | '/winner-resources/$token'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/criteria'
    | '/faq'
    | '/methodology'
    | '/pricing'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/winners'
    | '/winner-resources/$token'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  CriteriaRoute: typeof CriteriaRoute
  FaqRoute: typeof FaqRoute
  MethodologyRoute: typeof MethodologyRoute
  PricingRoute: typeof PricingRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ThankYouRoute: typeof ThankYouRoute
  WinnersRoute: typeof WinnersRoute
  WinnerResourcesTokenRoute: typeof WinnerResourcesTokenRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criteria': {
      id: '/criteria'
      path: '/criteria'
      fullPath: '/criteria'
      preLoaderRoute: typeof CriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winner-resources/$token': {
      id: '/winner-resources/$token'
      path: '/winner-resources/$token'
      fullPath: '/winner-resources/$token'
      preLoaderRoute: typeof WinnerResourcesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  CriteriaRoute: CriteriaRoute,
  FaqRoute: FaqRoute,
  MethodologyRoute: MethodologyRoute,
  PricingRoute: PricingRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ThankYouRoute: ThankYouRoute,
  WinnersRoute: WinnersRoute,
  WinnerResourcesTokenRoute: WinnerResourcesTokenRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
